### ISSUE TITLE
Tome Spits Up An Error When Asked to Install

### ISSUE THREAD

**Issue by nh-oriki** [N3X15/Tome#1]
```
Traceback (most recent call last):
File "<string>", line 205, in <module>
File "<string>", line 73, in CheckInstall
File "<string>", line 126, in WindowsInstallPHP
File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\buildtools.http", line 9, in DownloadFile
File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 127 in urlopen
File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 410, in open
File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 523, in http_response
File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 448, in error
File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 382, in _call_chain
File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 531, in http_error_default
urllib2.HTTPError: HTTP Error 404: Not Found
```

Some more things of note:
- Tome is being run as an administrator
- Tome was run in the  `C:\tome` folder
- I have no user named "Rob" on my PC.

**Comment by N3X15** [comment]
PHP probably just updated, I'll fix it.
On 5/20/2015 11:40 PM, Justin Lemke wrote:

> |Traceback (most recent call last):
> File "<string>", line 205, in <module>
> File "<string>", line 73, in CheckInstall
> File "<string>", line 126, in WindowsInstallPHP
> File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\buildtools.http", line 9, in DownloadFile
> File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 127 in urlopen
> File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 410, in open
> File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 523, in http_response
> File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 448, in error
> File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 382, in _call_chain
> File "C:\Users\Rob\Documents\Projects\tome\build\main\out00-PYZ.pyz\urllib2", line 531, in http_error_default
> urllib2.HTTPError: HTTP Error 404: Not Found
> |
> 
> Some more things of note:
> - Tome is being run as an administrator
> - Tome was run in the |C:\tome| folder
> - I have no user named "Rob" on my PC.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/N3X15/Tome/issues/1.

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by N3X15** [comment]
Tome's been updated.  

As for the weird stacktrace, that's pyinstaller trying to be helpful by displaying the original name of a compiled module, as it was on my computer when it was compiled.  That directory does not exist on your computer.
